services:
  - type: web
    name: autolike-dashboard
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    # PLUS BESOIN DE Environment Variables !
